LIBS-808 - Add support for prefetch count configuration
avides/spring-rabbit pull request #16
Opened 2022-02-23 13:52 UTC by fegbers

2022-02-23 13:58 UTC, fegbers commented
> Confluence/GitHub documentation added or updated?

README

2022-02-23 16:21 UTC, Schubi1981 requested changes

2022-02-24 08:54 UTC, bjoern-dirksen requested changes

2022-02-24 08:54 UTC, bjoern-dirksen commented on src/main/java/com/avides/spring/rabbit/configuration/util/DefaultValueResolver.java
>      }
Warum kein Einzeiler?
 return customValue != null ? customValue.intValue() : defaultValue.intValue();

2022-02-24 12:54 UTC, bjoern-dirksen approved these changes

2022-02-24 14:06 UTC, Schubi1981 approved these changes

2022-02-24 14:06 UTC, merged